name: build_go_env

on:
on:
  push:
    paths:
      - '.github/workflows/build_go_env.yml'
      - '.github/.version'
      - 'go-cuda_devel-ubuntu.Dockerfile'

env:
  REGISTRY: ghcr.io

jobs:
  build-go-cuda-devel:
    runs-on: ubuntu-latest
    needs: build-opencv-cuda-devel
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          
      - run: make go-cuda-devel